[phases.setup]
aptPkgs = ["ffmpeg"]

[phases.install]
cmds = [
  "apt-get update && apt-get install -y ffmpeg || true",
  "npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
